version: "3.7"

services:
  # image project
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - sonarnet
    ports:
      - '8080:8080'
      - '50000:50000'

  sonarqube:
      image: sonarqube:latest
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      networks:
        - sonarnet
      ports:
        - '9000:9000'
      #environment:
        #- sonar.jdbc.username=sonar
        #- sonar.jdbc.password=sonar
        #- sonar.jdbc.url=jdbc:postgresql://db:5432/sonar

  # db mysql
  db:
    container_name: mysql
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - '3306:3306'

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  jenkins_data:

